export enum GROUP_LAYOUT {
    IMAGE_GRID = "IMAGE_GRID",
    HIGHLIGHT = "HIGHLIGHT",
    CAROUSEL = "CAROUSEL",
    ICON_CAROUSEL = "ICON_CAROUSEL",
    LIST_HORIZONTAL = "LIST_HORIZONTAL",
    OVERLAP_LIST = "OVERLAP_LIST",
    SPECIAL_SELL_CAROUSEL = "SPECIAL_SELL_CAROUSEL",
    BANNER = "BANNER",
}

export enum GROUP_TYPE {
    SINGLE_PRODUCT = 'SINGLE_PRODUCT',
    PRODUCTS = 'PRODUCTS',
    SINGLE_CATEGORY = 'SINGLE_CATEGORY',
    CATEGORIES = 'CATEGORIES',
    SINGLE_BRAND = 'SINGLE_BRAND',
    BRANDS = 'BRANDS',
    SINGLE_COLLECTION = 'SINGLE_COLLECTION',
    COLLECTIONS = 'COLLECTIONS',
    SINGLE_PRODUCT_GROUP = 'SINGLE_PRODUCT_GROUP',
    PRODUCT_GROUPS = 'PRODUCT_GROUPS',
    SINGLE_SPECIAL_SALE = 'SINGLE_SPECIAL_SALE',
    SPECIAL_SALES = 'SPECIAL_SALES',
    SINGLE_BANNER = 'SINGLE_BANNER',
    BANNERS = 'BANNERS',
}
  
export enum GROUP_PLATFORM {
    WEB = 'WEB',
    MOBILE = 'MOBILE',
    COMMON = 'COMMON',
}

export enum GROUP_LINK_TYPE{
    INTERNAL = "INTERNAL",
    EXTERNAL = "EXTERNAL" 
}