export enum MEMBER_ROLE_MODULE {
    PRODUCT = "PRODUCT",
    PRODUCT_VARIATION = "PRODUCT_VARIATION",
    PRODUCT_VARIATION_VALUE = "PRODUCT_VARIATION_VALUE",
    PRODUCT_LABEL = "PRODUCT_LABEL",
    PRODUCT_GROUP = "PRODUCT_GROUP",
    SPECIAL_SALE = "SPECIAL_SALE",

    BANNER = "BANNER",
    CATEGORY = "CATEGORY",
    BRAND = "BRAND",
    COLLECTION = "COLLECTION",
    GROUP = "GROUP",
    PAGE = "PAGE",

    SEO_ITEM = "SEO_ITEM",
    CURRENCY = "CURRENCY",
    TAX_CATEGORY = "TAX_CATEGORY",
    
    USER = "USER",
    USER_SHIPPING_ADDRESS = "USER_SHIPPING_ADDRESS",
    MEMBER = "MEMBER",
    MEMBER_ROLE = "MEMBER_ROLE",
}

export enum PRODUCT_MODULE_FIELD {
    ITEM_CODE = "item_code",
    SAP_ID = "sap_id",
    NAME = "name",
    DESCRIPTION = "description",
    HIGHLIGHTS = "highlights",
    IMAGES = "images",
    YOUTUBE_VIDEO_ID = "youtube_video_id",
    SEARCH_KEYWORDS = "search_keywords",
    LABELS = "labels",
    CATEGORIES = "categories",
    BRANDS = "brands",
    TYPE = "type",
    ORDER_TYPE = "order_type",
    IS_PREORDER_ADVANCE_NEEDED = "is_preorder_advance_needed",
    PREORDER_ADVANCE_AMOUNT = "preorder_advance_amount",
    HAS_VARIANTS = "has_variants",
    VARIANTS = "variants",
    IS_VARIANT = "is_variant",
    MAIN_PRODUCT = "main_product",
    COST = "cost",
    PRICE = "price",
    OFFER_PRICE = "offer_price",
    TAX_CATEGORY = "tax_category",
    TAX_PERCENTAGE = "tax_percentage",
    TAXABLE_VALUE = "taxable_value",
    STOCK = "stock",
    MINIMUM_STOCK = "minimum_stock",
    MINIMUM_ORDER_QUANTITY = "minimum_order_quantity",
    MAXIMUM_ORDER_QUANTITY = "maximum_order_quantity",
    WEIGHT = "weight",
    DIMENSION = "dimension",
    IS_RETURN_VIABLE = "is_return_viable",
    IS_PAGE_ATTACHED = "is_page_attached",
    PAGE = "page",
    PRODUCT_GROUPS = "product_groups",
    WARRENTY = "warrenty",
    EXCHANGE_POLICY = "exchange_policy",
    IS_FREE_DELIVERY_PRODUCT = "is_free_delivery_product",
    IS_ACTIVE = "is_active",
    IS_DELETED = "is_deleted",
    CREATED_BY = "created_by",
    UPDATED_BY = "updated_by",

}

export enum MEMBER_ROLE_MODULE_FIELD {
    // Product
    ITEM_CODE = "item_code",
    SAP_ID = "sap_id",
    NAME = "name",
    DESCRIPTION = "description",
    HIGHLIGHTS = "highlights",
    IMAGES = "images",
    YOUTUBE_VIDEO_ID = "youtube_video_id",
    SEARCH_KEYWORDS = "search_keywords",
    LABELS = "labels",
    CATEGORIES = "categories",
    BRANDS = "brands",
    TYPE = "type",
    ORDER_TYPE = "order_type",
    IS_PREORDER_ADVANCE_NEEDED = "is_preorder_advance_needed",
    PREORDER_ADVANCE_AMOUNT = "preorder_advance_amount",
    HAS_VARIANTS = "has_variants",
    VARIANTS = "variants",
    IS_VARIANT = "is_variant",
    MAIN_PRODUCT = "main_product",
    COST = "cost",
    PRICE = "price",
    OFFER_PRICE = "offer_price",
    TAX_CATEGORY = "tax_category",
    TAX_PERCENTAGE = "tax_percentage",
    TAXABLE_VALUE = "taxable_value",
    STOCK = "stock",
    MINIMUM_STOCK = "minimum_stock",
    MINIMUM_ORDER_QUANTITY = "minimum_order_quantity",
    MAXIMUM_ORDER_QUANTITY = "maximum_order_quantity",
    WEIGHT = "weight",
    DIMENSION = "dimension",
    IS_RETURN_VIABLE = "is_return_viable",
    IS_PAGE_ATTACHED = "is_page_attached",
    PAGE = "page",
    PRODUCT_GROUPS = "product_groups",
    WARRENTY = "warrenty",
    EXCHANGE_POLICY = "exchange_policy",
    IS_FREE_DELIVERY_PRODUCT = "is_free_delivery_product",
    IS_ACTIVE = "is_active",
    IS_DELETED = "is_deleted",
    CREATED_BY = "created_by",
    UPDATED_BY = "updated_by",

}
