export enum ORDER_PAYMENT_TYPE {
    ONLINE = "ONLINE",
    COD = "COD",
}

export enum ORDER_TYPE {
    DIRECT = "DIRECT",
    PREORDER = "PREORDER" 
}

export enum ORDER_DELIVERY_TYPE {
    HOME_DELIVERY = 'HOME_DELIVERY',
    STORE_PICKUP = 'STORE_PICKUP',
}

export enum ORDER_SHIPPING_ADDRESS_TAG {
    HOME = "HOME",
    WORK = "WORK",
}

export enum ORDER_STATUS {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
    CANCEL_INITIATED = 'CANCEL_INITIATED',
    CANCELLED = 'CANCELLED',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    RETURN_INITIATED = 'RETURN_INITIATED',
    RETURNED = 'RETURNED',
}