export enum SETTINGS_USER_PAYMENT_OPTION {
    COD = 'COD',
    ONLINE = 'ONLINE',
    BOTH = 'BOTH'
}

export enum SETTINGS_GUEST_PAYMENT_OPTION {
    COD = 'COD',
    ONLINE = 'ONLINE',
    BOTH = 'BOTH'
}

export enum SETTINGS_USER_DELIVERY_OPTION {
    HOME_DELIVERY = 'HOME_DELIVERY',
    STORE_PICKUP = 'STORE_PICKUP',
    BOTH = 'BOTH'
}

export enum SETTINGS_GUEST_DELIVERY_OPTION {
    HOME_DELIVERY = 'HOME_DELIVERY',
    STORE_PICKUP = 'STORE_PICKUP',
    BOTH = 'BOTH'
}

export enum SETTINGS_SHIPPING_INPUT {
    NAME = 'NAME',
    FIRST_NAME = 'FIRST_NAME',
    MIDDLE_NAME = 'MIDDLE_NAME',
    LAST_NAME = 'LAST_NAME',
    EMAIL = 'EMAIL',
    PHONE = 'PHONE',
    ADDRESS = 'ADDRESS',
    ADDRESS_LINE_1 = 'ADDRESS_LINE_1',
    ADDRESS_LINE_2 = 'ADDRESS_LINE_2',
    STREET = 'STREET',
    LANDMARK = 'LANDMARK',
    AREA = 'AREA',
    CITY = 'CITY',
    DISTRICT = 'DISTRICT',
    STATE = 'STATE',
    COUNTRY = 'COUNTRY',
    PINCODE = 'PINCODE',
    WHATSAPP_NUMBER = 'WHATSAPP_NUMBER',
    IS_WHATSAPP_MESSAGING_AGREED = 'IS_WHATSAPP_MESSAGING_AGREED',
}

export enum SETTINGS_LAYOUT_LINK_TYPE {
    INTERNAL = 'INTERNAL',
    EXTERNAL = 'EXTERNAL',
}